package th.ac.kmitl.ce.ooad.cest.domain;

public enum Faculty
{
    ENGINEERING,
    ARCHITECTURE,
    INDUSTRIAL_EDUCATION,
    AGRICULTURAL_TECHNOLOGY,
    SCIENCE,
    AGRO_INDUSTRY,
    INFORMATION_TECHNOLOGY,
    INTERNATIONAL_COLLEGE,
    NANOTECHNOLOGY_COLLEGE,
    DATA_STORAGE_INNOVATION_COLLEGE,
    ADMINISTRATION_AND_MANAGEMENT_COLLEGE
}
